using AxioVital.Desktop.Models;
using Microsoft.UI.Xaml.Controls;
using System.Collections.Generic;

namespace AxioVital.Desktop.Views;

public sealed partial class MessageCenterView : UserControl
{
    public MessageCenterView()
    {
        this.InitializeComponent();
        MessageCenterItemsControl.ItemsSource = GetSampleMessageItems();
    }

    private static List<MessageCenterItem> GetSampleMessageItems()
    {
        return new List<MessageCenterItem>
        {
            new MessageCenterItem { PatientName = "JAMES, WILLIAM", PlanName = "CBC with Differential", Action = "Plan", DetailsDate = "05/28/17 08:30...", DetailsDesc = "Routine blood test", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 08:30", StopDate = "05/28/2017 08:30", StopType = "Physician Stop", Status = "Open", RowBackground = "#FFFFFF" },
            new MessageCenterItem { PatientName = "JAMES, WILLIAM", PlanName = "Comprehensive Metabolic Panel", Action = "Plan", DetailsDate = "05/28/17 08:30...", DetailsDesc = "Kidney & liver function", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 08:30", StopDate = "05/28/2017 08:30", StopType = "Physician Stop", Status = "Open", RowBackground = "#F4F8FA" },
            new MessageCenterItem { PatientName = "PATEL, RAHUL", PlanName = "MRI Brain W/O Contrast", Action = "Plan", DetailsDate = "05/28/17 09:15...", DetailsDesc = "Headache evaluation", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 09:15", StopDate = "05/28/2017 09:15", StopType = "Physician Stop", Status = "Open", RowBackground = "#FFFFFF" },
            new MessageCenterItem { PatientName = "PATEL, RAHUL", PlanName = "Referral to City Neuro Hospital", Action = "Referral", DetailsDate = "05/28/17 09:15...", DetailsDesc = "Transfer for advanced neuro care", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 09:15", StopDate = "05/28/2017 09:15", StopType = "Physician Stop", Status = "Open", RowBackground = "#F4F8FA" },
            new MessageCenterItem { PatientName = "JOHNSON, MARIA", PlanName = "PT Evaluation", Action = "Plan", DetailsDate = "05/28/17 10:00...", DetailsDesc = "Post-op rehab", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 10:00", StopDate = "05/28/2017 10:00", StopType = "Physician Stop", Status = "Open", RowBackground = "#FFFFFF" },
            new MessageCenterItem { PatientName = "JOHNSON, MARIA", PlanName = "Referral to St. Mary Regional Medical", Action = "Referral", DetailsDate = "05/28/17 10:00...", DetailsDesc = "Transfer for specialty pain mgmt", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 10:00", StopDate = "05/28/2017 10:00", StopType = "Physician Stop", Status = "Open", RowBackground = "#F4F8FA" },
            new MessageCenterItem { PatientName = "LEE, DAVID", PlanName = "Chest X-Ray", Action = "Plan", DetailsDate = "05/28/17 10:30...", DetailsDesc = "Cough and fever", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 10:30", StopDate = "05/28/2017 10:30", StopType = "Physician Stop", Status = "Open", RowBackground = "#FFFFFF" },
            new MessageCenterItem { PatientName = "LEE, DAVID", PlanName = "Sputum Culture", Action = "Plan", DetailsDate = "05/28/17 10:30...", DetailsDesc = "Infection workup", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 10:30", StopDate = "05/28/2017 10:30", StopType = "Physician Stop", Status = "Open", RowBackground = "#F4F8FA" },
            new MessageCenterItem { PatientName = "GARCIA, LUCIA", PlanName = "Echocardiogram", Action = "Plan", DetailsDate = "05/28/17 11:00...", DetailsDesc = "Cardiac evaluation", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 11:00", StopDate = "05/28/2017 11:00", StopType = "Physician Stop", Status = "Open", RowBackground = "#FFFFFF" },
            new MessageCenterItem { PatientName = "GARCIA, LUCIA", PlanName = "Referral to Metro Heart Institute", Action = "Referral", DetailsDate = "05/28/17 11:00...", DetailsDesc = "Transfer for cardiac surgery eval", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 11:00", StopDate = "05/28/2017 11:00", StopType = "Physician Stop", Status = "Open", RowBackground = "#F4F8FA" },
            new MessageCenterItem { PatientName = "KIM, JAMES", PlanName = "Hemoglobin A1C", Action = "Plan", DetailsDate = "05/28/17 11:30...", DetailsDesc = "Diabetes monitoring", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 11:30", StopDate = "05/28/2017 11:30", StopType = "Physician Stop", Status = "Open", RowBackground = "#FFFFFF" },
            new MessageCenterItem { PatientName = "KIM, JAMES", PlanName = "Diabetes Education", Action = "Plan", DetailsDate = "05/28/17 11:30...", DetailsDesc = "Patient education", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 11:30", StopDate = "05/28/2017 11:30", StopType = "Physician Stop", Status = "Open", RowBackground = "#F4F8FA" },
            new MessageCenterItem { PatientName = "BROWN, ELIZABETH", PlanName = "Urinalysis", Action = "Plan", DetailsDate = "05/28/17 12:00...", DetailsDesc = "UTI symptoms", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 12:00", StopDate = "05/28/2017 12:00", StopType = "Physician Stop", Status = "Open", RowBackground = "#FFFFFF" },
            new MessageCenterItem { PatientName = "BROWN, ELIZABETH", PlanName = "Urine Culture", Action = "Plan", DetailsDate = "05/28/17 12:00...", DetailsDesc = "Confirm infection", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 12:00", StopDate = "05/28/2017 12:00", StopType = "Physician Stop", Status = "Open", RowBackground = "#F4F8FA" },
            new MessageCenterItem { PatientName = "THOMAS, MICHAEL", PlanName = "CT Abdomen & Pelvis", Action = "Plan", DetailsDate = "05/28/17 12:30...", DetailsDesc = "Abdominal pain", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 12:30", StopDate = "05/28/2017 12:30", StopType = "Physician Stop", Status = "Open", RowBackground = "#FFFFFF" },
            new MessageCenterItem { PatientName = "THOMAS, MICHAEL", PlanName = "Referral to General Surgical Center", Action = "Referral", DetailsDate = "05/28/17 12:30...", DetailsDesc = "Transfer for emergency surgery", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 12:30", StopDate = "05/28/2017 12:30", StopType = "Physician Stop", Status = "Open", RowBackground = "#F4F8FA" },
            new MessageCenterItem { PatientName = "ANDERSON, SUSAN", PlanName = "Lipid Panel", Action = "Plan", DetailsDate = "05/28/17 13:00...", DetailsDesc = "Cholesterol check", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 13:00", StopDate = "05/28/2017 13:00", StopType = "Physician Stop", Status = "Open", RowBackground = "#FFFFFF" },
            new MessageCenterItem { PatientName = "ANDERSON, SUSAN", PlanName = "Nutrition Consult", Action = "Plan", DetailsDate = "05/28/17 13:00...", DetailsDesc = "Dietary counseling", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 13:00", StopDate = "05/28/2017 13:00", StopType = "Physician Stop", Status = "Open", RowBackground = "#F4F8FA" },
            new MessageCenterItem { PatientName = "MILLER, ROBERT", PlanName = "Pulmonary Function Test", Action = "Plan", DetailsDate = "05/28/17 13:30...", DetailsDesc = "COPD evaluation", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 13:30", StopDate = "05/28/2017 13:30", StopType = "Physician Stop", Status = "Open", RowBackground = "#FFFFFF" },
            new MessageCenterItem { PatientName = "MILLER, ROBERT", PlanName = "Referral to Pulmonary Care Hospital", Action = "Referral", DetailsDate = "05/28/17 13:30...", DetailsDesc = "Transfer for advanced COPD care", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 13:30", StopDate = "05/28/2017 13:30", StopType = "Physician Stop", Status = "Open", RowBackground = "#F4F8FA" },
            new MessageCenterItem { PatientName = "DAVIS, PATRICIA", PlanName = "DEXA Scan", Action = "Plan", DetailsDate = "05/28/17 14:00...", DetailsDesc = "Bone density", Comment = "AXIO, MD", OriginatorName = "AXIO, MD", CreateDate = "05/28/2017 14:00", StopDate = "05/28/2017 14:00", StopType = "Physician Stop", Status = "Open", RowBackground = "#FFFFFF" }
        };
    }
}
